kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc-0
  namespace: mongodb
  labels:
    app: prometheus-svc-0
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 9216
      targetPort: 9216
  selector:
    app: example-prometheus-svc
    statefulset.kubernetes.io/pod-name: example-prometheus-0
  type: NodePort
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc-1
  namespace: mongodb
  labels:
    app: prometheus-svc-1
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 9216
      targetPort: 9216
  selector:
    app: example-prometheus-svc
    statefulset.kubernetes.io/pod-name: example-prometheus-1
  type: NodePort
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc-2
  namespace: mongodb
  labels:
    app: prometheus-svc-2
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 9216
      targetPort: 9216
  selector:
    app: example-prometheus-svc
    statefulset.kubernetes.io/pod-name: example-prometheus-2
  type: NodePort
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
