---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1 # 变量: 副本数
  type: ReplicaSet
  version: 4.2.19 # 变量: 版本号，可支持版本： 4.0.28、4.2.19、4.4.13、5.0.8
  prometheus:
    # Metrics endpoint HTTP Basic Auth username
    username: Prometheus # 变量: Prometheus 监控用户,默认 Prometheus

    # Metrics endpoint HTTP Basic Auth password
    passwordSecretRef:
      name: metrics-endpoint-password

    # Optional, defaults to `/metrics`
    #metricsPath: /metrics

    # Optional defaults to 9216
    port: 9216 # 变量: Prometheus 监控端口,默认 9216

    # Prometheus endpoint can be configured to use HTTPS
    # tlsSecretKeyRef:
    #   name: "<kubernetes.io/tls secret name>"

  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: qc-master
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: qc-master
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: scram-qcmaster

    - name: root # 变量: 自定义用户
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: root # 变量: 自定义用户
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: scram-user


  additionalMongodConfig:
    systemLog:
      destination: file
      path: /data/mongod.log
    net:
      port: 27017  # 变量: mongodb 服务端口，默认 27017
    storage:
      wiredTiger:
        engineConfig:
          journalCompressor: zlib  # 数据压缩算法，不可更改
    replication:
      oplogSizeMB: 10240  # 变量: oplogSize 可修改，建议值: 磁盘大小的 5%

  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - name: mongod-posthook
              imagePullPolicy: IfNotPresent
            - name: mongodb-agent-readinessprobe
              imagePullPolicy: IfNotPresent
          containers:
            - name: mongod
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "8"
                  memory: 16G
                requests:
                  cpu: 2 # 变量: mongod cpu 大小
                  memory: 4G # 变量: mongod 内存大小
            - name: mongodb-agent
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 250M
          imagePullSecrets:
            - name: dockerhub  # 自定义镜像仓库 secret 配置， 需要提前创建该 secret

          volumeClaimTemplates:
            - metadata:
                name: data-volume
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 30G  # 变量: 存储空间， 可修改


# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: qc-master
type: Opaque
stringData:
  password: Zhu1241jie@

---
apiVersion: v1
kind: Secret
metadata:
  name: root # 变量: 自定义用户
type: Opaque
stringData:
  password: Zhu1241jie@ # 变量: 自定义用户密码

# Secret holding the prometheus metrics endpoint HTTP Password.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
subjects:
  - kind: ServiceAccount
    name: mongodb-database
roleRef:
  kind: Role
  name: mongodb-database
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXJodWIucWluZ2Nsb3VkLmNvbSI6eyJ1c2VybmFtZSI6ImNoZW54aW4iLCJwYXNzd29yZCI6Ilhpb25nMDMyMSIsImF1dGgiOiJZMmhsYm5ocGJqcFlhVzl1WnpBek1qRT0ifX19