---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.19"
  prometheus:
    # Metrics endpoint HTTP Basic Auth username
    username: promethus

    # Metrics endpoint HTTP Basic Auth password
    passwordSecretRef:
      name: metrics-endpoint-password

    # Optional, defaults to `/metrics`
    # metricsPath: /metrics

    # Optional defaults to 9216
    # port: 9216

    # Prometheus endpoint can be configured to use HTTPS
    # tlsSecretKeyRef:
    #   name: "<kubernetes.io/tls secret name>"

  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: qc_master
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram

    - name: shuaib
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: shuaib-ref
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram-test

  additionalMongodConfig:
    net:
      port: 27017
      maxIncomingConnections: 10000
    storage:
      wiredTiger:
        engineConfig:
          journalCompressor: zlib  # 数据压缩算法，不可更改
    replication:
      oplogSizeMB: 20480 # oplogSize 可修改，建议值: 磁盘大小的 5%
      enableMajorityReadConcern: true
    operationProfiling:
      mode: "off"
      slowOpThresholdMs: 100
    systemLog:
      destination: file
      path: /data/mongod.log
      logAppend: true
      logRotate: reopen
      component:
        command:
          verbosity: 0
        index:
          verbosity: 0
        query:
          verbosity: 0
        network:
          verbosity: 0
        write:
          verbosity: 0
    setParameter:
      cursorTimeoutMillis: 700000

  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - name: mongod-posthook
              imagePullPolicy: Always
            - name: mongodb-agent-readinessprobe
              imagePullPolicy: Always
          containers:
            - name: mongod
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "8"
                  memory: 16G
                requests:
                  cpu: "2"
                  memory: 2G
            - name: mongodb-agent
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi  # 存储空间， 可修改
#            storageClassName: csi-standard

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: Zhu1241jie@

---
apiVersion: v1
kind: Secret
metadata:
  name: shuaib-ref
type: Opaque
stringData:
  password: Zhu1241jie@

# Secret holding the prometheus metrics endpoint HTTP Password.
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: metrics-endpoint-password
#type: Opaque
#stringData:
#  password: promethus